ports:
  - port: 8080
    visibility: public
tasks:
  - before: |
      cp .env.sample .env
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack